heat_template_version: 2013-05-23

description: >
  TOSCA template for deploying an instance for DisVis

parameters:
  number_cpus:
    type: number
    description: number of cpus required for the instance
    default: 1
  memory_size:
    type: string
    description: ram memory required for the instance
    default: 1 GB
resources:
  disvis_configure_deploy:
    type: OS::Heat::SoftwareDeployment
    properties:
      input_values:
        haddock_app_name: disvis
      config:
        get_resource: disvis_configure_config
      server:
        get_resource: disvis-server
    depends_on:
    - disvis_install_roles_deploy
    - disvis-server_configure_deploy
  disvis-server:
    type: OS::Nova::Server
    properties:
      flavor: m1.small
      user_data_format: SOFTWARE_CONFIG
      image: ubuntu16-software-config-ifca
      networks:
          - network: provider-2050
  disvis_configure_config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ansible
      config:
        get_file: https://raw.githubusercontent.com/indigo-dc/tosca-types/master/artifacts/haddock/haddock_install.yml
  disvis_install_roles_config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: |
        #!/bin/bash
        ansible-galaxy install indigo-dc.disvis-powerfit
  disvis_install_roles_deploy:
    type: OS::Heat::SoftwareDeployment
    properties:
      config:
        get_resource: disvis_install_roles_config
      server:
        get_resource: disvis-server
  disvis-server_configure_config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ansible
      config:
        get_file: https://raw.githubusercontent.com/indigo-dc/tosca-types/master/artifacts/zabbix/zabbix_agent_install.yml
  disvis-server_configure_deploy:
    type: OS::Heat::SoftwareDeployment
    properties:
      input_values:
        zabbix_server_metadata: Linux      668c875e-9a39-4dc0-a710-17c41376c1e0
        zabbix_server_port: 10051
        zabbix_server: orchestrator.cloud.cnaf.infn.it
      config:
        get_resource: disvis-server_configure_config
      server:
        get_resource: disvis-server
    depends_on:
    - disvis-server_install_roles_deploy
  disvis-server_install_roles_config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: |
        #!/bin/bash
        rm -r /var/lib/dpkg/lock
        ansible-galaxy install indigo-dc.zabbix-agent
  disvis-server_install_roles_deploy:
    type: OS::Heat::SoftwareDeployment
    properties:
      config:
        get_resource: disvis-server_install_roles_config
      server:
        get_resource: disvis-server
outputs:
  instance_ip:
    value:
      get_attr:
      - disvis-server
      - networks
      - private
      - 0
