heat_template_version: 2013-05-23

description: >
  TOSCA example for specifying a Mesos Cluster

parameters:
  iam_token:
    type: string
    default: my_token
  cms_stageoutsite:
    type: string
    default: T1_IT_CNAF_Disk
  cms_local_site:
    type: string
    default: T3_IT_Opportunistic_pg
  cms_stageoutprefix_fallback:
    type: string
    default: DUMMY
  cms_stageoutsite_fallback:
    type: string
    default: DUMMY
  monitordb_ip:
    type: string
    default: 193.205.222.247:8080
  cms_stageoutserver:
    type: string
    default: storm-fe-cms.cr.cnaf.infn.it
  iam_client_id:
    type: string
    default: myclient_id
  cms_stageoutserver_fallback:
    type: string
    default: DUMMY
  cms_stageoutprefix:
    type: string
    default: srm://storm-fe-cms.cr.cnaf.infn.it:8444/srm/managerv2?SFN=/cmsdisk/
  elasticsearch_secret:
    type: string
    default: 5z0O87gnSf
  iam_client_secret:
    type: string
    default: myclient_secret
resources:
  mesos-master-server:
    type: OS::Nova::Server
    properties:
      flavor: m1.large
      user_data_format: SOFTWARE_CONFIG
      image: ubuntu16-heat-ifca
      networks:
          - network: 2b729f05-cda2-4316-bab6-4247aa06d708
  mesos_slave_create_deploy:
    type: OS::Heat::SoftwareDeployment
    properties:
      input_values:
        front_end_ip:
          get_attr:
          - mesos-master-server
          - networks
          - private
          - 0
        enable_nfs_share:
          get_property:
          - SELF
          - enable_nfs_share
        mesos_masters_list_ips:
          get_attr:
          - mesos-master-server
          - networks
          - private
          - 0
      config:
        get_resource: mesos_slave_create_config
      server:
        get_resource: mesos-slave-server
    depends_on:
    - mesos-slave-server_configure_deploy
  mesos-slave-server:
    type: OS::Nova::Server
    properties:
      flavor: m1.medium
      user_data_format: SOFTWARE_CONFIG
      image: ubuntu16-heat-ifca
      networks:
          - network: 2b729f05-cda2-4316-bab6-4247aa06d708
  mesos_load_balancer_create_deploy:
    type: OS::Heat::SoftwareDeployment
    properties:
      input_values:
        consul_server_ips:
          get_attr:
          - mesos-master-server
          - networks
          - private
          - 0
        marathon_password: test_pass
        marathon_username: admin
      config:
        get_resource: mesos_load_balancer_create_config
      server:
        get_resource: mesos-lb-server
    depends_on:
    - mesos-lb-server_configure_deploy
  cms_services_start_deploy:
    type: OS::Heat::SoftwareDeployment
    properties:
      input_values:
        cms_config_proxycache_host:
          get_attr:
          - mesos-lb-server
          - networks
          - private
          - 0
        cms_config_squid_image: spiga/frontiersquidv1
        cms_config_iam_client_id:
          get_param: iam_client_id
        cms_config_cms_local_site:
          get_param: cms_local_site
        cms_config_iamtoken:
          get_param: iam_token
        marathon_user: admin
        marathon_pass: test_pass
        cms_config_wn_image: spiga/cmswn
        cms_config_mysquid_host:
          get_attr:
          - mesos-lb-server
          - networks
          - private
          - 0
        cms_config_iam_client_secret:
          get_param: iam_client_secret
        cms_config_proxycache_image: spiga/ttscache
      config:
        get_resource: cms_services_start_config
      server:
        get_resource: mesos-master-server
    depends_on:
    - cms_services_install_roles_deploy
    - mesos_master_configure_deploy
  cms_wn_configure_deploy:
    type: OS::Heat::SoftwareDeployment
    properties:
      input_values:
        cms_config_proxycache_host:
          get_attr:
          - mesos-lb-server
          - networks
          - private
          - 0
        cms_config_stageoutserver:
          get_param: cms_stageoutserver
        cms_config_cms_local_site:
          get_param: cms_local_site
        monitordb_ip:
          get_param: monitordb_ip
        cms_config_stageoutprefix_fallback:
          get_param: cms_stageoutprefix_fallback
        cms_config_stageoutserver_fallback:
          get_param: cms_stageoutserver_fallback
        cms_config_stageoutprefix:
          get_param: cms_stageoutprefix
        cms_config_mysquid_host:
          get_attr:
          - mesos-lb-server
          - networks
          - private
          - 0
        cms_config_elastic_secret:
          get_param: elasticsearch_secret
        cms_config_stageoutsite:
          get_param: cms_stageoutsite
        cms_config_stageoutsite_fallback:
          get_param: cms_stageoutsite_fallback
      config:
        get_resource: cms_wn_configure_config
      server:
        get_resource: mesos-slave-server
    depends_on:
    - cms_wn_install_roles_deploy
    - mesos_slave_create_deploy
  mesos_master_configure_deploy:
    type: OS::Heat::SoftwareDeployment
    properties:
      input_values:
        chronos_user: admin
        marathon_enable_ssl: true
        chronos_pass: test_pass
        enable_chronos: true
        chronos_enable_ssl: true
        marathon_user: admin
        marathon_pass: test_pass
        wn_ips:
          get_property:
          - SELF
          - wn_ips
        enable_nfs_share:
          get_property:
          - SELF
          - enable_nfs_share
        mesos_masters_list_ips:
          get_attr:
          - mesos-master-server
          - networks
          - private
          - 0
      config:
        get_resource: mesos_master_configure_config
      server:
        get_resource: mesos-master-server
    depends_on:
    - mesos_master_install_roles_deploy
    - mesos-master-server_configure_deploy
  mesos-lb-server:
    type: OS::Nova::Server
    properties:
      flavor: m1.medium
      user_data_format: SOFTWARE_CONFIG
      image: ubuntu16-heat-ifca
      networks:
          - network: 2b729f05-cda2-4316-bab6-4247aa06d708
  mesos-master-server_configure_config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ansible
      config:
        get_file: https://raw.githubusercontent.com/indigo-dc/tosca-types/master/artifacts/zabbix/zabbix_agent_install.yml
  mesos-master-server_configure_deploy:
    type: OS::Heat::SoftwareDeployment
    properties:
      input_values:
        zabbix_server_metadata: Linux      668c875e-9a39-4dc0-a710-17c41376c1e0
        zabbix_server_port: 10051
        zabbix_server: orchestrator.cloud.cnaf.infn.it
      config:
        get_resource: mesos-master-server_configure_config
      server:
        get_resource: mesos-master-server
    depends_on:
    - mesos-master-server_install_roles_deploy
  mesos-master-server_install_roles_config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: |
        #!/bin/bash
        ansible-galaxy install indigo-dc.zabbix-agent
  mesos-master-server_install_roles_deploy:
    type: OS::Heat::SoftwareDeployment
    properties:
      config:
        get_resource: mesos-master-server_install_roles_config
      server:
        get_resource: mesos-master-server
  mesos_slave_create_config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ansible
      config:
        get_file: https://raw.githubusercontent.com/indigo-dc/tosca-types/master/artifacts/mesos/mesos_slave_install.yml
  mesos_slave_install_roles_config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: |
        #!/bin/bash
        ansible-galaxy install indigo-dc.docker
        ansible-galaxy install indigo-dc.consul
        ansible-galaxy install indigo-dc.nfs
        ansible-galaxy install indigo-dc.mesos
  mesos_slave_install_roles_deploy:
    type: OS::Heat::SoftwareDeployment
    properties:
      config:
        get_resource: mesos_slave_install_roles_config
      server:
        get_resource: mesos-slave-server
  mesos-slave-server_configure_config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ansible
      config:
        get_file: https://raw.githubusercontent.com/indigo-dc/tosca-types/master/artifacts/zabbix/zabbix_agent_install.yml
  mesos-slave-server_configure_deploy:
    type: OS::Heat::SoftwareDeployment
    properties:
      input_values:
        zabbix_server_metadata: Linux      668c875e-9a39-4dc0-a710-17c41376c1e0
        zabbix_server_port: 10051
        zabbix_server: orchestrator.cloud.cnaf.infn.it
      config:
        get_resource: mesos-slave-server_configure_config
      server:
        get_resource: mesos-slave-server
    depends_on:
    - mesos-slave-server_install_roles_deploy
  mesos-slave-server_install_roles_config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: |
        #!/bin/bash
        ansible-galaxy install indigo-dc.zabbix-agent
  mesos-slave-server_install_roles_deploy:
    type: OS::Heat::SoftwareDeployment
    properties:
      config:
        get_resource: mesos-slave-server_install_roles_config
      server:
        get_resource: mesos-slave-server
  mesos_load_balancer_create_config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ansible
      config:
        get_file: https://raw.githubusercontent.com/indigo-dc/tosca-types/master/artifacts/mesos/mesos_lb_install.yml
  mesos_load_balancer_install_roles_config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: |
        #!/bin/bash
        ansible-galaxy install indigo-dc.docker
        ansible-galaxy install indigo-dc.consul
        ansible-galaxy install indigo-dc.marathon-lb
  mesos_load_balancer_install_roles_deploy:
    type: OS::Heat::SoftwareDeployment
    properties:
      config:
        get_resource: mesos_load_balancer_install_roles_config
      server:
        get_resource: mesos-lb-server
  cms_services_start_config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ansible
      config:
        get_file: https://raw.githubusercontent.com/indigo-dc/tosca-types/master/artifacts/mesos/cms_services_start.yml
  cms_services_install_roles_config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: |
        #!/bin/bash
        ansible-galaxy install indigo-dc.cms_config
  cms_services_install_roles_deploy:
    type: OS::Heat::SoftwareDeployment
    properties:
      config:
        get_resource: cms_services_install_roles_config
      server:
        get_resource: mesos-master-server
  cms_wn_configure_config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ansible
      config:
        get_file: https://raw.githubusercontent.com/indigo-dc/tosca-types/master/artifacts/mesos/cms_wn_configure.yml
  cms_wn_install_roles_config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: |
        #!/bin/bash
        ansible-galaxy install indigo-dc.cms_config
  cms_wn_install_roles_deploy:
    type: OS::Heat::SoftwareDeployment
    properties:
      config:
        get_resource: cms_wn_install_roles_config
      server:
        get_resource: mesos-slave-server
  mesos_master_configure_config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ansible
      config:
        get_file: https://raw.githubusercontent.com/indigo-dc/tosca-types/master/artifacts/mesos/mesos_master_install.yml
  mesos_master_install_roles_config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: |
        #!/bin/bash
        ansible-galaxy install indigo-dc.consul
        ansible-galaxy install indigo-dc.marathon
        ansible-galaxy install indigo-dc.docker
        ansible-galaxy install indigo-dc.zookeeper
        ansible-galaxy install indigo-dc.mesos
        ansible-galaxy install indigo-dc.nfs
        ansible-galaxy install indigo-dc.chronos
  mesos_master_install_roles_deploy:
    type: OS::Heat::SoftwareDeployment
    properties:
      config:
        get_resource: mesos_master_install_roles_config
      server:
        get_resource: mesos-master-server
  mesos-lb-server_configure_config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ansible
      config:
        get_file: https://raw.githubusercontent.com/indigo-dc/tosca-types/master/artifacts/zabbix/zabbix_agent_install.yml
  mesos-lb-server_configure_deploy:
    type: OS::Heat::SoftwareDeployment
    properties:
      input_values:
        zabbix_server_metadata: Linux      668c875e-9a39-4dc0-a710-17c41376c1e0
        zabbix_server_port: 10051
        zabbix_server: orchestrator.cloud.cnaf.infn.it
      config:
        get_resource: mesos-lb-server_configure_config
      server:
        get_resource: mesos-lb-server
    depends_on:
    - mesos-lb-server_install_roles_deploy
  mesos-lb-server_install_roles_config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: |
        #!/bin/bash
        ansible-galaxy install indigo-dc.zabbix-agent
  mesos-lb-server_install_roles_deploy:
    type: OS::Heat::SoftwareDeployment
    properties:
      config:
        get_resource: mesos-lb-server_install_roles_config
      server:
        get_resource: mesos-lb-server
outputs:
  mesos_endpoint:
    value:
      str_replace:
        params:
          $s2: :5050
          $s0: http://
          $s1:
            get_attr:
            - mesos-master-server
            - networks
            - private
            - 0
        template: $s0$s1$s2
  mesos_lb_ip:
    value:
      get_attr:
      - mesos-lb-server
      - networks
      - private
      - 0
  marathon_endpoint:
    value:
      str_replace:
        params:
          $s2: :8080
          $s0: http://
          $s1:
            get_attr:
            - mesos-master-server
            - networks
            - private
            - 0
        template: $s0$s1$s2
